pool: Plex Hosted Ubuntu 1604
trigger: none

steps:
  - task: UseDotNet@2
    displayName: Use .NET 5.0
    inputs:
      version: "5.0.x"
      packageType: sdk
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      workingDirectory: source/
